[versions]
# libraries
junit-jupiter = "6.0.1"
kotest = "6.1.0"
ktlint = "1.3.1"

# plugins
kotlin = "2.3.0"
kotlinx-serialization = "1.9.0"
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
qodana = "2025.3.1"
kover = "0.9.4"

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.0.1" }
